name: Run tests and deploy to AWS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Deploy to AWS EC2
        uses: easingthemes/ssh-deploy@main
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          remote-user: ubuntu
          server-ip: ${{ secrets.EC2_PUBLIC_IP }}
          remote-path: /var/www/chasbank
          local-path: .
