name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Copy project to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "/home/ubuntu/chas-banksajt-cicd"

      - name: SSH and run docker-compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/chas-banksajt-cicd

            # Stäng av gamla containrar och ta bort gamla containrar och nätverk
            sudo docker-compose down || true
            sudo docker rm -f $(docker ps -aq) || true
            sudo docker network prune -f || true

            # Rensa gamla images och containrar
            sudo docker system prune -af

            # Bygg och starta om containrar
            sudo docker-compose up --build -d
